# Generated by Django 2.0.4 on 2018-07-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
                ('micro_dust', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
